import { Nunito } from 'next/font/google';
import Navbar from './components/navbar/navbar.component';

import './globals.css'
import RegisterModal from './components/modals/register-modal';
import ToasterProvider from './components/providers/toaster.provider';
import LoginModal from './components/modals/login-modal';
import getCurrentUser from './actions/getCurrentUser';
import RentModal from './components/modals/rent-modal';
import SearchModal from './components/modals/search-modal';
import Footer from './components/footer';

export const metadata = {
  title: 'AirBnb',
  description: 'AirBnb Clone Generated by create next app',
}

const font = Nunito({
  subsets: ['latin'],
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <ToasterProvider />
        <RentModal />
        <SearchModal />
        <LoginModal />
        <RegisterModal />
        <Navbar currentUser={currentUser} />
        <div className='pb-20 pt-28'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
